name: Go Chat App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18' 

    - name: Get dependencies
      run: go mod download

    - name: Test
      run: go test ./...

    - name: Build
      run: go build -v .

    # Deployment step - you'll need to customize this depending on your hosting provider
    # - name: Deploy
    #   run: |
    #     # Your deployment script or commands here
